services:
    custom_task_event_subscriber:
        class: CustomBundle\Biz\Task\Event\TaskSyncSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    custom_activity_event_subscriber:
        class: CustomBundle\Biz\Activity\Event\CustomActivitySubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    custom_course_event_subscriber:
        class: CustomBundle\Biz\Course\Event\CustomCourseSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    custom_sign_in_event_subscriber:
        class: CustomBundle\Biz\SignIn\Event\CustomSignInSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    socket_push_event_subscriber:
        class: CustomBundle\Biz\Course\Event\SocketPushSubscriber
        arguments: ['@biz', '@service_container']
        tags:
            - { name: codeages_plugin.event.subscriber }
    
    cunston_lesson_record_event_subscriber:
        class: CustomBundle\Biz\Lesson\Event\LessonRecordSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    custom_lesson_teaching_aims_event_subscriber:
        class: CustomBundle\Biz\Lesson\Event\TeachingAimSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }